### PR TITLE
refactor; remove some of the bad code

### PR DESCRIPTION
**Pull request by mustafaquraish**

### CODE REVIEW

**Comment by HavenSelph** [comment]
Needs cargo fmt

**Comment by timotheyca** [comment]
lgtm

**Comment by andreaslam** [comment]
kmerge!!!

**Comment by HavenSelph** [comment]
alright looks good, will come to ruse 2027

**Comment by andreaslam** [comment]
!remindme 2027

**Review by timotheyca — CHANGES_REQUESTED** [review]
why does github not allow me to write an empty message here lol

**Review by HavenSelph — CHANGES_REQUESTED** [review]
yeah these look okay but make them better

**Comment by nerd-bear** [comment]
LGTM! I say push to prod

**Review by HavenSelph — CHANGES_REQUESTED** [review]
need license for 1997 please

**Comment by HavenSelph** [comment]
hold on didn't see it there

**Comment by andreaslam** [comment]
missing license for year 3.14159265358979323846264338327950288419716939937510

**Comment by HavenSelph** [comment]
lgtm

**Review by HavenSelph — APPROVED** [review]

**Pull request merged**
